      <!-- Page Header Start -->
      <div class="page-header" style="background: url(<?=base_url('assets/website/img/banner1.jpg');?>); ">
        <div class="container">
          <div class="row">         
            <div class="col-md-12">
              <div class="breadcrumb-wrapper">
                <h2 class="product-title">Terms and Conditions</h2>
                <ol class="breadcrumb">
                  <li><a href="<?=base_url();?>"><i class="ti-home"></i> Home</a></li>
                  <li class="current">Terms and Conditions</li>
                </ol>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- Page Header End -->        

    <section class="section">
          <div class="container">
                <p>PLEASE READ THESE TERMS AND CONDITIONS CAREFULLY. BY ACCESSING OR USING THIS WEB SITE, USERS AGREE TO BE BOUND BY THE TERMS AND CONDITIONS INCLUDED HEREIN AND ALL TERMS, CONDITIONS, AND DISCLOSURES INCORPORATED HEREIN BY REFERENCE. IF USERS DO NOT AGREE TO ALL OF THESE TERMS AND CONDITIONS, DO NOT USE THIS WEBSITE.  THE USE OF THE WEBSITE CONSTITUTES YOUR AGREEMENT TO THESE TERMS AND CONDITIONS.</p>
                <p>These Terms and Conditions (also referred to as “Site Terms" and “Agreement” herein) apply exclusively to Users access to, and use of, the website operated by ……………….., located at www.biladl.com and the information and other services provided therein (the "Services"). These Site Terms do not alter the terms or conditions of any other agreement Users may have with BILADL, or its subsidiaries or affiliates, for products, services or otherwise. If Users are using the Site on behalf of any person or entity, Users must legally represent and warrant that they are appointed authorized to sign up to BILADL’s Site Terms on such entity's behalf, and that such entity agrees to indemnify Users and BILADL for violations of these Site Terms.</p>
                <p>BILADL reserves the right to change or modify any of the Site Terms or any policy or process of the Site at any time and in its sole discretion. BILADL will provide notice of any and all changes by posting the revised Site Terms on the Site and indicating on the Site Terms the date they were last updated. Any revisions or modifications to the Site Terms will be effective immediately upon posting of the revisions or modifications on the Site. Users continued use of this Site following the posting of revised or modified Site Terms will constitute Users acceptance of such revisions or modifications. If Users do not agree to the revised or modified Site Terms, Users must stop using the Site immediately.</p>
                <br />
                <h4>THE BILADL SITE.</h4>
                <br/>
                <h5>1.1Definitions</h5>
                <ol>
                    <li>"Terms and Conditions," “Site Terms,” and “Agreement” all mean these Terms and Conditions;</li>
                    <li>“BILADL,” "us," "we," "our," and any other reference made in the first person means BILADL;</li>
                    <li>The “Site” means the website operated by BILADL, LLC, at web address www.biladl.com;</li>
                    <li>The “Services” means all services provided by BILADL, LLC to all users of the Site;</li>
                    <li>“Attorneys” means those users of the Site being, and holding themselves out on the Site as being, attorneys licensed to practice law in Saudi Arabia;</li>
                    <li>“Clients” means those users of the Site holding themselves out on the Site as being legal persons or entities looking for and needing legal services;</li>
                    <li>“Users” or “User” means the legal persons or entities using the Site, including both Attorneys and Clients, and accepting these Site Terms and Agreement;</li>
                    <li>"Premium Subscription," "Premium Services," "Premium Membership," and "Premium Account” means the service available to Attorneys by the Site that allows Attorneys to apply directly to Clients for legal jobs posted on the Site by those Clients in exchange for payment of an annual fee to BILADL and any other paid services offered by BILADL on the Site;</li>
                    <li>Definitions of additional terms are included in throughout these Site Terms and those additional terms shall have the definitions attributed to them therein; all words, terms, and phrases not defined in these Site Terms shall be given their commonly understood meaning.</li>
                </ol>
                <h5>1.2 Purpose of the BILADL Site.</h5>
                <p>The Site allows Clients and Attorneys to find, locate, contact one another, share information, and initially connect with one another online. Thus, if Clients and Attorneys want, they can connect and enter into agreements for legal services with one another Online under BILADL’s involvement. Under these Site Terms, BILADL provides no services to Clients other than providing them with a forum to find, locate, identify, share information, post legal jobs, and initially connect with Attorneys online. Under this Agreement, BILADL provides no services to Attorneys other than providing them with a forum to find, contact, and share information with Clients online, review Client’s posted legal jobs, and, if an attorney has a “Premium Account,” allowing the Attorneys to respond directly to Clients’ legal job postings. BILADL is a not a law firm and does not refer Clients to Attorneys or Attorneys to Clients. BILADL does not independently verify that the Attorneys using the Site are licensed and insured to practice law, that they are competent legal service providers, or that the information posted to the Site or provided to Clients by Attorneys is accurate. Instead, BILADL relies solely on the Attorneys to verify that they are licensed and insured to practice law in the States identified, competent legal service providers, and that the information posted to the Site or provided to Clients is accurate. Before hiring or retaining Attorneys offline, Clients should independently verify that the Attorneys are licensed and insured to practice law in the States identified, competent legal service providers, and that the information posted to the Site or provided to Clients by Attorneys is accurate.</p>
                <h4>2. BILADL GENERAL USER POLICIES</h4>
                <h5>2.1 General User Obligations.</h5>
                <p>Users will not access or attempt to access the Site by any means other than the mechanism provided, and will not use information from the Site for any purpose other than the purpose for which it was made available. Users will not engage in any activity that interferes with or disrupts the functioning of the Site. Users will not upload or attach invalid, malicious, or unknown files to the Site. Users will not insert any external links that are malicious or unknown to Users, or used for offering any goods or services other than the services for which the Site is intended. Users agree not to scrape, take, or acquire data from the Site, whether by manual or automated means, for any commercial, marketing, or data compiling or enhancing purpose, or to copy, re-post or re-use data from the Site for any other service. Users agree not to use or provide software, except for general purpose web browsers and email clients, or software expressly licensed by BILADL, or services that interact or communicate with the Site for downloading, uploading, posting, flagging, emailing, search, or mobile use.</p>
                <h5>2.2 Identity and Account Security.</h5>
                <p>BILADL reserves the right, but is not obligated, to validate Users’ information at any time, including, but not limited to, validation against third party databases or the verification of one or more official government or legal documents that confirm the Users’ identity. Users authorize BILADL, directly or through third parties, to make any inquiries necessary to validate Users’ identity and confirm Users’ ownership of Users’ email address or financial accounts, subject to applicable laws. Users' failure to provide information about Users and Users’ business when requested is a violation of this Agreement. Users are solely responsible for ensuring and maintaining the secrecy and security of their passwords used to access their account on the Site. Users agree not to disclose their password to anyone and shall be solely responsible for any use of, action taken, or damages incurred through the improper use of such passwords on the Site. Users must notify the Site immediately if Users suspect that their password have been lost or stolen. By using the Site, Users acknowledge and agree the BILADL's account security procedures are commercially reasonable.</p>
                <h5>2.3 Enforcement of Agreement and Policies.</h5>
                <p>BILADL has the right, but not the obligation, to suspend or cancel Users access to the Site if it reasonably believes that Users have violated or acted inconsistently with the aim of this Agreement or violated the rights of Users or any other party. Without limiting BILADL's other remedies, it may suspend or terminate Users account, use self-help in connection with rights to reclaim any available funds, and refuse to provide any further access to the BILADL Site to Users if: (a) Users breach any terms and conditions of this Agreement or other written policies and procedures posted on the Site; (b) we are unable to verify or authenticate any information Users provide to us; (c) we believe that Users actions may cause legal liability for or damage to Users or BILADL; or (d) we believed that Users use of the Site does not conform with the intent and purpose of the Site. Once suspended or terminated, Users MAY NOT continue to use the BILADL Site under a different account or re-register under a new account. If Users attempt to use the BILADL Site under a different account, we reserve the right to take whatever steps necessary to prevent that and make BILADL or any other impacted party whole. In addition, violations of this Agreement may be prosecuted to the fullest extent of the law and may result in additional damages, penalties, fines, and sanctions being assessed. When Users account is suspended or terminated, Users may no longer have access to any parts of the BILADL Site, including data, messages, files and other material Users keep on BILADL.</p>
                <h5>2.4 Consent to Receive Emails</h5>
                <p>By using the Site, Users consent to receive emails from BILADL, which may include commercial emails provided such emails are in accordance with the preferences Users select in Notifications page of their Homepage. Users may change such preferences by changing Users account settings on the Notifications page. Please note that as long as Users maintain an account, Users may not "opt out" of receiving service or account-related emails from BILADL. </p>
                <h5>2.5 Copyright and Limited License</h5>
                <p>Unless otherwise indicated, the Site and all content and other materials on the Site, including, without limitation, the BILADL logo, and all designs, text, graphics, pictures, reviews, information, data, software, sound files, other files and the selection and arrangement thereof (collectively, the "Site Materials") are the proprietary property of BILADL or its licensors or Users and are protected by Saudi Arabia. and international copyright laws.</p>
                <p>Users are granted a limited, non-assignable license to access and use the Site and electronically copy, (except where prohibited without a license) and print to hard copy portions of the Site Materials for Users informational, non-commercial and personal use only.  Such license is subject to these Site Terms and does not include or authorize: (a) any resale or commercial use of the Site or the Site Materials therein; (b) the collection and use of any professional listings, pictures, profiles, ratings or descriptions; (c) the distribution, public performance or public display of any Site Materials, (d) modifying or otherwise making any derivative uses of the Site and the Site Materials, or any portion thereof; (e) use of any data mining, robots or similar data gathering or extraction methods; (f) downloading (other than the page caching) of any portion of the Site, the Site Materials or any information contained therein, except as expressly permitted on the Site; or (g) any use of the Site or the Site Materials other than for its intended purpose. Any use of the Site or the Site Materials other than as specifically authorized herein, without the prior written permission of BILADL, is strictly prohibited and will terminate the license granted herein. Such unauthorized use may also violate applicable laws including without limitation copyright and trademark laws and applicable communications regulations and statutes. Unless explicitly stated herein, nothing in these Site Terms shall be construed as conferring any license to intellectual property rights, whether by estoppel, implication or otherwise. This license is revocable at any time.</p>
                <p>Should any person, entity, or User of the Site believes that their work has been reproduced on the Site in a way that constitutes copyright infringement, that person, entity, or User may notify BILADL's copyright agent a) identification of the copyrighted work that you claim has been infringed; b) identification of the material that you claim is infringing and needs to be removed, including a description of where it is located on the Site so that the copyright agent can locate it; c) your address, telephone number, and, if available, e-mail address, so that the copyright agent may contact you about your complaint; and d) a signed statement that the above information is accurate; that you have a good faith belief that the identified use of the material is not authorized by the copyright owner, its agent, or the law; and, under penalty of perjury, that you are the copyright owner or are authorized to act on the copyright owner's behalf in this situation. Notices of copyright infringement claims should be sent to (mail) (Email).  If you give notice of copyright infringement by email, we may begin investigating the alleged copyright infringement; however, we must receive your signed statement by mail or as an attachment to your e-mail before we are required to take any action.</p>
                <h5>2.6 Trademarks</h5>
                <p>BILADL logo and any other product or service name or slogan contained in the Site are trademarks of BILADL and its suppliers or licensors, and may not be copied, imitated or used, in whole or in part, without the prior written permission of BILADL or the applicable trademark holder. Users may not use any meta-tags or any other "hidden text" utilizing "BILADL" or any other name, trademark or product or service name of BILADL without our prior written permission. In addition, the indications of distinctive signs of the Site, including all page headers, custom graphics, button icons and scripts, is the service mark, trademark and/or trade dress of BILADL and may not be copied, imitated or used, in whole or in part, without our prior written permission. All other trademarks, registered trademarks, product names and BILADL names or logos mentioned in the Site are the property of their respective owners.</p>
                <h5>2.7 Hyperlinks</h5>
                <p>Users are granted a limited, non-exclusive right to create a text hyperlink to the Site for noncommercial purposes, provided such link does not portray BILADL, any of its products and services, or any professional or professional services entity in a false, misleading, derogatory or otherwise defamatory manner and provided further that the linking site does not contain any adult or illegal material or any material that is offensive, harassing or otherwise objectionable. This limited right may be revoked at any time. Users may not use BILADL’s logo or other proprietary graphics of BILADL to link to this Site without the express written permission of BILADL. Furthermore, Users may not use, frame or utilize framing techniques to enclose any of BILADL trademark, logo or other proprietary information, including the images found at the Site, the content of any text or the layout/design of any page or form contained on a page on the Site without BILADL’s express written consent. Except as noted above, Users are not conveyed any right or license by implication, estoppel or otherwise in or under any patent, trademark, copyright or proprietary right of BILADL or any third party.</p>
                <p>BILADL makes no claim or representation regarding, and accepts no responsibility for, the quality, content, nature or reliability of third-party Web sites accessible via hyperlink from the Site, or Web sites linking to the Site. Such sites are not under the control of BILADL and BILADL is not responsible for the contents of any linked site or any link contained in a linked site, or any review, changes or updates to such sites. BILADL provides these links to Users only as a convenience, and the inclusion of any link does not imply affiliation, endorsement or adoption by BILADL of any site or any information contained therein. When Users leave the Site, Users should be aware that our terms, conditions, and policies may no longer apply. Users should review the applicable terms, conditions, and policies, including privacy and data gathering practices, of any site to which Users navigate from the Site.</p>
                <h5>2.8 Premium Services</h5>
                <p>BILADL offers optional Premium Services to Attorneys including the ability to directly respond to Client’s posted legal jobs. By selecting a Premium Service, Attorneys agree to pay BILADL the subscription or usage fees indicated for that service. Payments for subscription services will be charged on the day Attorney’s Premium Service goes into effect and will cover the use of that service for a period of one year.  Attorneys agree that annual payments will continue to be charged to their credit card on a recurring basis until they cancel their Premium Service on the Site. The amount of the annual recurring charge will be the then current subscription fee applicable to the Premium Service. Attorneys acknowledge that the amount of the recurring charge may increase if the applicable subscription fee increases. Premium Services may be cancelled on the Site prior to the annual renewal in order to avoid next year’s Premium Service fee. Premium Service fees are not prorated or refundable. If the payment method fails or the account is past due, BILADL reserves the right to either suspend or terminate the Attorney’s Premium Services. Any such suspension or termination will result in the cancellation of any Attorney’s Premium Services.  Attorneys agree to submit any disputes regarding any charge to their account in writing to BILADL within sixty (60) days of such charge, otherwise, the charge will be considered final and accepted by the Attorney and such dispute will be waived and such charge will not subject to legal challenge. All BILADL fees for its Premium Services are non-refundable, whether or not the Attorney actually enters into an agreements or contracts for legal services with Clients offline.</p>
                <h5>2.9 Non-Payment.</h5>
                <p>If Attorneys fail to pay amounts due under this Agreement for their Premium Services, whether by cancelling Client's credit card or any other means, Attorney’s BILADL account will be suspended. Without limiting other available remedies, Attorneys must reimburse BILADL for amounts outstanding at the time of their failure to pay upon demand, plus any applicable processing fees, charges or penalties, , plus attorneys' fees and other costs of collection as allowed by law.</p>
                <p>Users Failure of payment: If users of BILADL services fail to pay outstanding amounts which are required from them in order for the service to be performed, BILADL, their account could be suspended or terminated. Without limiting other available remedies, users must reimburse BILADL for amounts outstanding at the time of their failure to pay upon demand, plus any applicable processing fees, charges or penalties, , plus attorneys' fees and other costs of collection as allowed by law.</p>
                <h5>2.10 Third Party Content</h5>
                <p>BILADL or users may provide links to web pages and content of third parties as a service to those interested in such links and content, and BILADL may post third party content or allow users to post their content or third party content to the Site (such content is collectively referred to as “Third Party Content”). BILADL does not monitor or have any control over any Third Party Content or third party web sites. BILADL does not endorse or adopt any Third Party Content or third party website and does not make any guarantee as to its accuracy or completeness. BILADL does not represent or warrant the accuracy of any information contained therein and undertakes no responsibility to update or review any Third Party Content or third party websites. Users agree to use these links, Third Party Content and third party websites at their own risk.</p>
                <h5>2.11 Third Party Services</h5>
                <p>The Site may also contain, provide information regarding, or link to certain applications and services provided or offered by third parties (collectively the "Third-Party Services"), including, without limitation, information related to professional services. BILADL is merely an information provider and is not a referral service, and it does not recommend or endorse any such Third-Party Services or monitor or have any control over such Third-Party Services. Therefore, BILADL makes no guarantee, representation or warranty of any kinds as to the quality, competency, value, reliability, responsiveness, accuracy or completeness of any such Third-Party Services or the results obtained therefrom, and BILADL assumes no responsibility or liability to Users for any Third Party Services or for the actions or failure to act of those providing such Third-Party Services. Users undertake full responsibility for Users use of any such Third-Party Services, and BILADL is not responsible or liable to Users for any Third-Party Services.</p>
                <h5>2.12 Advertisements and Promotions</h5>
                <p>BILADL may run advertisements and promotions for and from third parties on the Site. Users business dealings or correspondence with, or participation in promotions of advertisers other than BILADL, and any terms, conditions, warranties or representations associated with such dealings, are solely between Users and such third party. BILADL is not responsible or liable for any loss or damage of any sort incurred by Users as the result of any such dealings or as the result of the presence of such advertisers on the Site other than BILADL.</p>
                <h5>2.13 Professional Advertising and Communications</h5>

<p>It is solely the responsibility of Attorneys to ensure that any information or advertisements they post or place on the Site, and any communications they may have with Clients through the Site and the Services, fully comply with all applicable laws and rules of professional conduct, including those concerning the unauthorized practice of law and those regulating the form, ,or content of communications with clients, advertising, or other matters.</p>

<h5>2.14 Submissions</h5>

<p>Users acknowledge and agree that any materials, including, but not limited to, questions, comments, reviews, job or legal need postings, suggestions, ideas, feedback, plans, notes, original or creative materials, or other information provided by Users in the form of email or other submissions to or on the Site, or any postings on the Site, are non-confidential and shall become the sole property of BILADL. BILADL shall own exclusive rights, including all intellectual property rights, and shall be entitled to the unrestricted use, modification, and dissemination of these materials for any purpose, commercial or otherwise, without acknowledgment or compensation to Users.  Users expressly acknowledge that BILADL may modify the content of any job or legal needs postings by Clients to ensure that the postings are capable of being understood by, and are disseminated to, the appropriate Attorneys, as determined in BILADL's sole discretion.  </p>

<h5>2.15 User Posted Content & Other Interactive Services or Areas</h5>

<p>The Site includes areas in which Users may post content and information, including, without limitation, ratings and reviews, messages, questions and answers, guides, comments, data, text, photos, graphics or other materials (the "User Content") and may include other interactive areas or services in which Users or third parties may create, post, modify or store information, content, materials or other items on the Site ("Interactive Areas"). Users are solely responsible for Users use of such Interactive Areas and use them at Users own risk. By using any Interactive Areas, Users agree not to post, upload to, transmit, distribute, store, create or otherwise publish through the Site any of the following:</p>
<ol>
<li>  User Content that is false, misleading, unlawful, libelous, defamatory, obscene, pornographic, indecent, lewd, suggestive, harassing, threatening, invasive of privacy or publicity rights, abusive, inflammatory, fraudulent or otherwise objectionable, including without limitation any recommendation, endorsement, rating, or review of Attorneys with whom Users have not had direct, personal experience in a professional context or as a client of such professional; </li>

<li>  User Content that would constitute, encourage, or provide instructions for a criminal offense, violate the rights of any party, violate any applicable rules of professional conduct, or that would otherwise create liability or violate any local, state, national or international law;  </li>

<li>  User Content that may infringe any patent, trademark, trade secret, copyright or other intellectual or proprietary right of any party. By posting any User Content, Users represent and warrant that Users have the lawful right to distribute and reproduce such User Content as provided under these Site Terms; </li>

<li>  User Content that impersonates any person or entity or otherwise misrepresents Users affiliation with a person or entity;  </li>

<li>  Unsolicited promotions, political campaigning, advertising or solicitations, including without limitation any advertisements for professional services, professional service providers, or professional referral services; </li>
 
<li>  Private or confidential information of any third party, including, without limitation, addresses, phone numbers, email addresses, Social Security numbers and credit card numbers; </li>

<li>  Viruses, spyware, malware, corrupted data or other harmful, disruptive or destructive files; </li>

<li>  Any answers, responses, comments, opinions, analysis or recommendations that Users are not properly licensed or otherwise qualified to provide; and  </li>

<li>  User Content that, in the sole judgment of BILADL, is objectionable or which restricts or inhibits any other person from using or enjoying the Interactive Areas or the Site, or which may expose BILADL or its Users to any harm or liability of any type. </li>
</ol>

<p>BILADL takes no responsibility and holds no liability for any User Content posted, stored, or uploaded by Users or any third party, or for any loss or damage thereto, nor is BILADL liable for any mistakes, defamation, slander, libel, omissions, falsehoods, obscenity, pornography, or profanity Users may encounter or post on the Site. Users use of Interactive Areas is at Users own risk. Enforcement of the User Content or conduct rules set forth in these Site Terms is solely at BILADL's discretion, and failure to enforce such rules in some instances does not constitute a waiver of our right to enforce such rules in other instances. In addition, these rules do not create any private right of action on behalf of Users or any third party or any reasonable expectation that the Site will not contain any content that is prohibited by such terms, conditions, policies, and rules. As a provider of interactive services, BILADL is not liable for any statements, representations, responses, comments or other User Content provided by its Users in any review, rating, forum, question, answer, guide or other Interactive Area. Although BILADL has no obligation to screen, edit, or monitor any of the User Content posted in any Interactive Area, BILADL reserves the right, and has absolute discretion, to remove, screen, or edit any User Content posted or stored on the Site at any time and for any reason without notice. Any use of the Interactive Areas or other portions of the Site in violation of the foregoing violates these Site Terms and may result in, among other things, termination or suspension of Users rights to use the Interactive Areas and/or the Site. </p>


<p>If Users post User Content to the Site, Users grant BILADL and its affiliates a nonexclusive, royalty-free, perpetual, irrevocable, and fully sub-licensable right to use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, perform and display such User Content throughout the world in any media. Users grant BILADL and its affiliates and sub-licensees the right to use the name that Users submit in connection with such User Content, if they choose. Users represent and warrant that: (a) Users own and control all of the rights to the User Content that Users post or Users otherwise have the right to post such User Content to the Site and to grant the rights granted herein; (b) the User Content is accurate and not misleading; and (c) use and posting of the User Content Users supply does not violate these Site Terms and will not violate any rights of or cause injury to any person or entity.</p>

<h5>2.16 Registration of Data; Account Security</h5>


<p>In consideration of Users use of the Site, Users agree to: (a) provide accurate, current and complete information about Users as may be prompted by any registration forms on the Site ("Registration Data"); (b) maintain the security of Users password and identification; (c) maintain and promptly update the Registration Data and to keep all other information Users provide to BILADL accurate, current, and complete; and (d) accept all risks of unauthorized access to the Registration Data and any other information Users provide to BILADL. In addition, Users agree not to access or use, or attempt to access or use, the Site or any part thereof using the identity or the Registration Data of any person other than User.</p>

<h4>3. ACKNOWLEDGMENTS BY USERS OF BILADL’s ROLE.</h4>
<h5>3.1 BILADL’s Role.</h5>


<p>Users expressly acknowledge, agree, and understand that: 1) BILADL’s Site is merely a platform where Users may identify one another, share information, and initially connect with one another online, so, if Clients and Attorneys so desire and we do not encourage such action, they can connect and enter into agreements for legal services offline, without BILADL’s involvement, at a later time; 2) BILADL is not a party to any contracts or agreement between Attorneys and Clients made offline; 3) Users are not employees of BILADL and BILADL does not, in any way, supervise, direct, or control Users, their actions, their statements, their representations, or their work; 4) BILADL shall not have any liability or obligations under or related to any contracts or agreements entered into between Users or for any acts or omissions by Users; 5) BILADL has no control over Users or over the services promised or rendered by Users; and, 6) BILADL makes no representations as to the reliability, capability, or qualifications of any Attorney or the quality, appropriateness, or legality of any legal services, and BILADL disclaims any and all liability relating thereto. </p>

<h5>3.2  No Attorney-Client Relationship</h5>


<p>Information posted or made available on or through the Site, including, without limitation, legal job postings, any responses to legal job postings or questions posted on the Site, information provided in articles on the Site, and any other comments, opinions, recommendations, answers, analysis, references, referrals or legally related content or information (collectively "Legal Information") is not intended as legal advice or to create an attorney-client or attorney-prospective client relationship between Client(s) and Attorney(s). Such Legal Information is intended for general informational purposes only. It is not a substitute for an in-person or telephone consultation with an attorney licensed to practice in the appropriate jurisdiction and qualified to address that specific legal issue, and Users should not rely upon such Legal Information. Users understand that questions and answers or other postings to the Site are not confidential and are not subject to attorney-client privilege. Client(s) understand that no information disclosed in a legal job posting will prohibit Attorney(s) on the Site from representing a different client in the same legal matter if no attorney-client or attorney-prospective client relationship is established off-line.</p>

<h4>4. INVOICES AND PAYMENT METHODS. </h4>
<h5>4.1 Payment Methods.</h5>
<p>Attorneys having Premium Accounts hereby authorizes BILADL to run credit card authorizations on all credit cards provided by Attorneys, to store credit card details as method of payment for Services, and to charge the credit card or process any other form of payment authorized by BILADL or mutually agreed to between Attorneys and BILADL.  All credit card information will be stored with PayPal (paypal.com), and Attorneys purchasing Premium Services agree to accept PayPal's terms and conditions as applicable to their transactions.  Deduction of payment? Renewed automatically or manually? If auto, refund possible within a short period? Check amazon. </p>
<h4>5. WARRANTY DISCLAIMER AND OTHER DISCLAIMERS</h4>
<p>the site, the site materials (including any professional information) and the services are provided on an "as is" and "as available" basis without warranties of any kind, either express or implied. BILADL disclaims all warranties, express or implied, including, without limitation, implied warranties of merchantability, fitness for a particular purpose, title and non-infringement as to the information, content or materials in the site. BILADL does not represent or warrant that site materials, including the information available in or on the site, or the services are accurate, complete, reliable, current or error-free. BILADL does not represent or warrant that the site or its servers are free of viruses or other harmful components.</p>
<p>While BILADL endeavors to provide, and to allow others to provide, useful information regarding attorneys and professional services, Users acknowledge that such information is reliant upon third party data and contributions, that there are certain inherent limitations to the accuracy or currency of such information, that professional and other information may be incomplete or may contain inaccuracies, and that information on the Site may be outdated or contain errors, omissions or misinterpretations of information. Neither BILADL Ratings, Professional Information nor any of the other information contained on the Site or provided through the Services, are an endorsement of any particular Attorney or are a guarantee of an Attorney's quality, competency, qualifications, experience, resources, character, honesty, integrity, responsiveness or other personal and professional characteristics. Nor are they a predictor of the outcome of any matter in which such Attorney is involved. The information provided on this Site is intended to be a starting point to gather information about Attorneys who may be suitable for Users legal needs, but Users should not rely solely on such information in deciding whether to hire any given attorney. Furthermore, Users should independently verify the accuracy of any information Users obtain on the Site before using it, and Users should obtain independent references for any Attorneys that Clients are considering hiring. Users agree to be solely responsible for their use of the Site, the Site Materials and the Services and for determining the suitability of, and the results obtained from, any Attorneys that Clients hire.</p>

<p>Users acknowledge and agree that Users use of the Site, or of any information or features in or on the Site, is informed by and subject not only to these Disclaimers, but also by the information and explanation available on these pages.</p>

<p>BILADL reserves the right to change any and all content contained in the Site and any Services offered through the Site at any time without notice. Reference to any professionals, professional service providers or organizations, educational institutions, associations, organizations, publications, licenses, accreditations, ratings, evaluations, endorsements, reviews, products, services, processes or other information, by name, trade name, trademark, manufacturer, supplier or otherwise does not constitute or imply endorsement, sponsorship or recommendation thereof, or any affiliation therewith, by BILADL.</p>
<h4>6. LIMITATION OF LIABILITY.</h4>
<p>in no event will BILADL be liable to users for any direct, special, consequential, incidental, exemplary, or indirect costs or damages, litigation costs, attorneys’ fees, installation and removal costs, or loss of data, production or profit.</p>

<p>in no event shall BILADL or any of its corporate affiliates, independent contractors, service providers, or consultants, or any of their respective directors, employees and agents, be liable for any direct, special, indirect, or consequential damages, or any other damages of any kind, including but not limited to the outcome of legal matters, loss of use, loss of profits or loss of data, whether in an action in contract, tort (including, but not limited to, negligence) or otherwise, arising out of or in any way related to or connected with any use of the site, the services, the content or the materials contained in or accessed through the site, including, without limitation, any damages, loss or injury caused by or resulting from reliance by user on any information obtained from BILADL or the site, or that result from mistakes, omissions, interruptions, deletion of files or email, errors, defects, viruses, delays in operation, or transmission or any failure of performance, whether or not resulting from acts of god, communications failure, theft, destruction or unauthorized BILADL’s records, programs or services. if not otherwise properly disclaimed, the aggregate liability of BILADL, whether in contract, warranty, tort (including negligence, whether active, passive or imputed), product liability, strict liability or other theory, arising out of or relating in any manner to the use of the site or the site materials, shall not exceed any compensation users paid to BILADL in the one-year period preceding the date user’s alleged claim first arose, if any, to BILADL for access to or use of the site.</p>

<p>in no event shall BILADL be liable in any manner for either physical or psychiatric injuries to attorneys or users suffered by the services provided directly or indirectly from BILADL. by using BILADL services, attorneys and users cannot sue BILADL for physical or psychiatric injury suffered directly or indirectly by BILADL. </p>
<h4>7. INDEMNIFICATION.</h4>
<h5>7.1 Proprietary Rights.</h5>
<p>Each User shall defend, indemnify, and hold harmless BILADL and its subsidiaries, affiliates, officers, agents, employees, representatives and agents (each an "Indemnified Party" for purposes of this Section 7) from any and all claims, damages, liabilities, costs, and expenses (including, but not limited to, reasonable attorneys' fees and all related costs and expenses) arising from or relating to any claim, judgment, or adjudication that any information, services, or action or omission that such User infringes on the proprietary rights of BILADL or other rights of any third party.</p>
<h5>7.2 Indemnification by User.</h5>
<p>Each User shall defend, indemnify, and hold harmless the Indemnified Parties from any and all claims, damages, liabilities, costs, and expenses (including, but not limited to, reasonable attorneys' fees and all related costs and expenses) arising from or relating to information or services provided, or actions taken, by that User.</p>
<h4>8. TERM AND TERMINATION.</h4>
<h5>8.1 Term.</h5>
<p>The term of this Agreement commences on the Effective Date and continues in effect until terminated in accordance with Section 8.2 below.</p>
<h5>8.2 Termination.</h5>
<p>BILADL may terminate this Agreement or Users use of the Site at any time, with or without cause, effective immediately without written notice to the Users.</p>
<h5>8.3 Consequences of Termination.</h5>
<p>Termination shall not relieve Users of the requirement to pay for use of the Site incurred prior to the effective date of the termination. </p>

<h4>9. GENERAL.</h4>
<h5>9.1 Entire Agreement.</h5>
<p>This Agreement sets forth the entire agreement and understanding of the parties relating to its subject matter and cancels and supersedes any prior or contemporaneous discussions, agreements, representations, warranties, and other communications between them.</p>

<h5>9.2 Compliance.</h5>
<p>Users shall not violate any laws or third party rights on or related to the use of the Site. Without limiting the generality of the foregoing, Users agree to comply with all applicable import and export control laws and third parties' proprietary rights.</p>

<h5>9.3 Notices: Consent to Electronic Notice.</h5>
<p>Users consent to the use of (a) electronic means to complete this Agreement and to deliver any notices pursuant to this Agreement; and (b) electronic records to store information related to this Agreement or Users’ use of the Site.</p>

<h5>9.4 Modifications.</h5>
<p>No modification or amendment to this Agreement shall be binding upon BILADL unless in a written instrument signed by a duly authorized representative of BILADL. For the purposes of this Section 9.4, a written instrument shall expressly exclude electronic communications, such as email and facsimiles.</p>

<h5>9.5 No Waiver.</h5>
<p>The failure or delay of BILADL to exercise or enforce any right or claim does not constitute a waiver of such right or claim, and shall in no way affect its right to later enforce or exercise it, unless it issues an express written waiver, signed by a duly authorized representative of it.</p>

<h5>9.6 Assignability.</h5>
<p>Users may not assign this Agreement, or any of its rights or obligations here under, without BILADL's prior written consent in the form of a written instrument signed by a duly authorized representative of BILADL (and, for the purposes of this Section 9.6, a written instrument shall expressly exclude electronic communications such as email and facsimiles). BILADL may freely assign this Agreement without consent of Users. Any attempted assignment or transfer in violation of this Section will be null and void. Subject to the foregoing restrictions, this Agreement will inure to the benefit of the successors and permitted assigns of BILADL.</p>

<h5>9.7 Severability.</h5>
<p>If and to the extent any provision of this Agreement is held illegal, invalid, or unenforceable in whole or in part under applicable law, such provision or such portion thereof shall be ineffective as to the jurisdiction in which it is illegal, invalid, or unenforceable to the extent of its illegality, invalidity, or unenforceability, and shall be deemed modified to the extent necessary to conform to applicable law so as to give the maximum effect to the intent of the parties. The illegality, invalidity, or unenforceability of such provision in that jurisdiction shall not in any way affect the legality, validity, or enforceability of such provision in any other jurisdiction or of any other provision in any jurisdiction.</p>

<h5>9.8 Choice of Law.</h5>
<p>This Agreement and any controversy, dispute, lawsuit, or claim arising out of or relating to this Agreement, ("Claims") shall be governed by and construed in accordance with the laws of the kingdom of Saudi Arabia.</p>

<h5>9.9 Dispute Resolution; Arbitration; Personal Jurisdiction and Venue.</h5>
<p>BILADL and Users hereby agree that any Claims shall first be settled through negotiation. If a Claim (other than a Claim for injunctive or other equitable relief) remains unresolved by these means, BILADL will have the right to demand binding, non-appearance based arbitration by a third party service selected by BILADL. The arbitration shall take place in Chicago, Illinois, and in the event the parties cannot agree on a third party service or an arbitrator, BILADL shall have the right select the third party service and/or the arbitrator. A final judgment will be made by the arbitrator, which must be adhered to by all parties. Users agree that any Claim Users may have against BILADL, if not resolved as set forth above, must be resolved by the Illinois state courts of DuPage County (or, if there is exclusive federal jurisdiction, the United States District Court for the Northern District of Illinois). Users hereby irrevocably consent to the personal jurisdiction and venue of these courts.</p>

<h5>9.10 Prevailing Language.</h5>
<p>The English language version of this Agreement shall be controlling in all respects and shall prevail in case of any inconsistencies with translated versions, if any.</p>


            </div>
          </div>
    </section>
